name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: 
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-musl

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from Git tag
        id: extract_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/v}"

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            PLATFORM=${{ matrix.platform }}
            VERSION=${{ steps.extract_version.outputs.VERSION }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rathole:${{ matrix.platform }}-latest
            ghcr.io/${{ github.repository_owner }}/rathole:${{ matrix.platform }}-v${{ steps.extract_version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            PLATFORM=${{ matrix.platform }}
            VERSION=${{ steps.extract_version.outputs.VERSION }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/rathole:${{ matrix.platform }}-latest
            ${{ secrets.DOCKER_USERNAME }}/rathole:${{ matrix.platform }}-v${{ steps.extract_version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64
