name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: 
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from Git tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            PLATFORM=${{ matrix.platform }}
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rathole:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/rathole:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/rathole:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/rathole:latest
          platforms: linux/amd64,linux/arm64
